# Generated by Django 4.1.13 on 2026-02-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='landing/', verbose_name='Изображение')),
                ('start_at', models.DateField(verbose_name='Дата начала показа')),
                ('end_at', models.DateField(verbose_name='Дата окончания показа (включительно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включён?')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Промо-баннер',
                'verbose_name_plural': 'Промо-баннеры',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_has_whatsapp',
            field=models.BooleanField(editable=False, verbose_name='Имеется Telegram'),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='measure',
            field=models.CharField(choices=[('л', 'литр'), ('кг', 'килограмм'), ('шт', 'штука'), ('г', 'грамм')], default=('шт', 'штука'), max_length=4, verbose_name='Ед. измерения'),
        ),
    ]
